// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/order/order.proto

/*
Package go_micro_service_order is a generated protocol buffer package.

It is generated from these files:
	proto/order/order.proto

It has these top-level messages:
	OrderId
	OrderInfo
	OrderDetail
	OrderPageRequest
	OrderPageConditions
	OrderPagedList
	Response
	PayStatus
	ShipStatus
*/
package go_micro_service_order

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import google_protobuf1 "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Timestamp from public import google/protobuf/timestamp.proto
type Timestamp google_protobuf.Timestamp

func (m *Timestamp) Reset()            { (*google_protobuf.Timestamp)(m).Reset() }
func (m *Timestamp) String() string    { return (*google_protobuf.Timestamp)(m).String() }
func (*Timestamp) ProtoMessage()       {}
func (m *Timestamp) GetSeconds() int64 { return (*google_protobuf.Timestamp)(m).GetSeconds() }
func (m *Timestamp) GetNanos() int32   { return (*google_protobuf.Timestamp)(m).GetNanos() }

// Any from public import google/protobuf/any.proto
type Any google_protobuf1.Any

func (m *Any) Reset()             { (*google_protobuf1.Any)(m).Reset() }
func (m *Any) String() string     { return (*google_protobuf1.Any)(m).String() }
func (*Any) ProtoMessage()        {}
func (m *Any) GetTypeUrl() string { return (*google_protobuf1.Any)(m).GetTypeUrl() }
func (m *Any) GetValue() []byte   { return (*google_protobuf1.Any)(m).GetValue() }

type OrderId struct {
	OrderId int64 `protobuf:"varint,1,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
}

func (m *OrderId) Reset()                    { *m = OrderId{} }
func (m *OrderId) String() string            { return proto.CompactTextString(m) }
func (*OrderId) ProtoMessage()               {}
func (*OrderId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *OrderId) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

type OrderInfo struct {
	Id          int64          `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	PayStatus   int32          `protobuf:"varint,2,opt,name=pay_status,json=payStatus" json:"pay_status,omitempty"`
	ShipStatus  int32          `protobuf:"varint,3,opt,name=ship_status,json=shipStatus" json:"ship_status,omitempty"`
	Price       float64        `protobuf:"fixed64,4,opt,name=price" json:"price,omitempty"`
	OrderDetail []*OrderDetail `protobuf:"bytes,5,rep,name=order_detail,json=orderDetail" json:"order_detail,omitempty"`
}

func (m *OrderInfo) Reset()                    { *m = OrderInfo{} }
func (m *OrderInfo) String() string            { return proto.CompactTextString(m) }
func (*OrderInfo) ProtoMessage()               {}
func (*OrderInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *OrderInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrderInfo) GetPayStatus() int32 {
	if m != nil {
		return m.PayStatus
	}
	return 0
}

func (m *OrderInfo) GetShipStatus() int32 {
	if m != nil {
		return m.ShipStatus
	}
	return 0
}

func (m *OrderInfo) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderInfo) GetOrderDetail() []*OrderDetail {
	if m != nil {
		return m.OrderDetail
	}
	return nil
}

type OrderDetail struct {
	Id            int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	ProductId     int64 `protobuf:"varint,2,opt,name=product_id,json=productId" json:"product_id,omitempty"`
	ProductNum    int32 `protobuf:"varint,3,opt,name=product_num,json=productNum" json:"product_num,omitempty"`
	ProductSizeId int64 `protobuf:"varint,4,opt,name=product_size_id,json=productSizeId" json:"product_size_id,omitempty"`
	ProductPrice  int64 `protobuf:"varint,5,opt,name=product_price,json=productPrice" json:"product_price,omitempty"`
	OrderId       int64 `protobuf:"varint,6,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
}

func (m *OrderDetail) Reset()                    { *m = OrderDetail{} }
func (m *OrderDetail) String() string            { return proto.CompactTextString(m) }
func (*OrderDetail) ProtoMessage()               {}
func (*OrderDetail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *OrderDetail) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrderDetail) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *OrderDetail) GetProductNum() int32 {
	if m != nil {
		return m.ProductNum
	}
	return 0
}

func (m *OrderDetail) GetProductSizeId() int64 {
	if m != nil {
		return m.ProductSizeId
	}
	return 0
}

func (m *OrderDetail) GetProductPrice() int64 {
	if m != nil {
		return m.ProductPrice
	}
	return 0
}

func (m *OrderDetail) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

type OrderPageRequest struct {
	Page       int64                `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	PageSize   int64                `protobuf:"varint,2,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	Conditions *OrderPageConditions `protobuf:"bytes,3,opt,name=conditions" json:"conditions,omitempty"`
}

func (m *OrderPageRequest) Reset()                    { *m = OrderPageRequest{} }
func (m *OrderPageRequest) String() string            { return proto.CompactTextString(m) }
func (*OrderPageRequest) ProtoMessage()               {}
func (*OrderPageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *OrderPageRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *OrderPageRequest) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *OrderPageRequest) GetConditions() *OrderPageConditions {
	if m != nil {
		return m.Conditions
	}
	return nil
}

type OrderPageConditions struct {
	PayStatus      int32                      `protobuf:"varint,1,opt,name=pay_status,json=payStatus" json:"pay_status,omitempty"`
	ShipStatus     int32                      `protobuf:"varint,2,opt,name=ship_status,json=shipStatus" json:"ship_status,omitempty"`
	OrderCode      string                     `protobuf:"bytes,3,opt,name=OrderCode" json:"OrderCode,omitempty"`
	OrderStartTime *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=order_start_time,json=orderStartTime" json:"order_start_time,omitempty"`
	OrderEndTime   *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=order_end_time,json=orderEndTime" json:"order_end_time,omitempty"`
}

func (m *OrderPageConditions) Reset()                    { *m = OrderPageConditions{} }
func (m *OrderPageConditions) String() string            { return proto.CompactTextString(m) }
func (*OrderPageConditions) ProtoMessage()               {}
func (*OrderPageConditions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *OrderPageConditions) GetPayStatus() int32 {
	if m != nil {
		return m.PayStatus
	}
	return 0
}

func (m *OrderPageConditions) GetShipStatus() int32 {
	if m != nil {
		return m.ShipStatus
	}
	return 0
}

func (m *OrderPageConditions) GetOrderCode() string {
	if m != nil {
		return m.OrderCode
	}
	return ""
}

func (m *OrderPageConditions) GetOrderStartTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.OrderStartTime
	}
	return nil
}

func (m *OrderPageConditions) GetOrderEndTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.OrderEndTime
	}
	return nil
}

type OrderPagedList struct {
	Total    int64        `protobuf:"varint,1,opt,name=total" json:"total,omitempty"`
	Page     int64        `protobuf:"varint,2,opt,name=page" json:"page,omitempty"`
	PageSize int64        `protobuf:"varint,3,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	Pages    int64        `protobuf:"varint,4,opt,name=pages" json:"pages,omitempty"`
	Data     []*OrderInfo `protobuf:"bytes,5,rep,name=Data" json:"Data,omitempty"`
}

func (m *OrderPagedList) Reset()                    { *m = OrderPagedList{} }
func (m *OrderPagedList) String() string            { return proto.CompactTextString(m) }
func (*OrderPagedList) ProtoMessage()               {}
func (*OrderPagedList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *OrderPagedList) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *OrderPagedList) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *OrderPagedList) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *OrderPagedList) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *OrderPagedList) GetData() []*OrderInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type Response struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type PayStatus struct {
	OrderId   int64 `protobuf:"varint,1,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	PayStatus int32 `protobuf:"varint,2,opt,name=pay_status,json=payStatus" json:"pay_status,omitempty"`
}

func (m *PayStatus) Reset()                    { *m = PayStatus{} }
func (m *PayStatus) String() string            { return proto.CompactTextString(m) }
func (*PayStatus) ProtoMessage()               {}
func (*PayStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PayStatus) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *PayStatus) GetPayStatus() int32 {
	if m != nil {
		return m.PayStatus
	}
	return 0
}

type ShipStatus struct {
	OrderId    int64 `protobuf:"varint,1,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	ShipStatus int32 `protobuf:"varint,2,opt,name=ship_status,json=shipStatus" json:"ship_status,omitempty"`
}

func (m *ShipStatus) Reset()                    { *m = ShipStatus{} }
func (m *ShipStatus) String() string            { return proto.CompactTextString(m) }
func (*ShipStatus) ProtoMessage()               {}
func (*ShipStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ShipStatus) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *ShipStatus) GetShipStatus() int32 {
	if m != nil {
		return m.ShipStatus
	}
	return 0
}

func init() {
	proto.RegisterType((*OrderId)(nil), "go.micro.service.order.OrderId")
	proto.RegisterType((*OrderInfo)(nil), "go.micro.service.order.OrderInfo")
	proto.RegisterType((*OrderDetail)(nil), "go.micro.service.order.OrderDetail")
	proto.RegisterType((*OrderPageRequest)(nil), "go.micro.service.order.OrderPageRequest")
	proto.RegisterType((*OrderPageConditions)(nil), "go.micro.service.order.OrderPageConditions")
	proto.RegisterType((*OrderPagedList)(nil), "go.micro.service.order.OrderPagedList")
	proto.RegisterType((*Response)(nil), "go.micro.service.order.Response")
	proto.RegisterType((*PayStatus)(nil), "go.micro.service.order.PayStatus")
	proto.RegisterType((*ShipStatus)(nil), "go.micro.service.order.ShipStatus")
}

func init() { proto.RegisterFile("proto/order/order.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 695 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x6e, 0xd3, 0x48,
	0x14, 0x8e, 0x93, 0xb8, 0xad, 0x8f, 0xbb, 0x6d, 0x77, 0xb6, 0xbb, 0x9b, 0x86, 0xa2, 0x86, 0x29,
	0xaa, 0x22, 0x21, 0xb9, 0x52, 0x10, 0xf7, 0x88, 0xa6, 0x40, 0x05, 0x82, 0xc8, 0x29, 0xdc, 0xa1,
	0x68, 0x9a, 0x99, 0x9a, 0x91, 0x12, 0x8f, 0xf1, 0x4c, 0x90, 0xd2, 0x37, 0xe0, 0x8e, 0x87, 0xe0,
	0x25, 0x78, 0x00, 0x9e, 0x8a, 0x1b, 0x34, 0x3f, 0x4e, 0x42, 0x69, 0xe2, 0xdc, 0x24, 0x9e, 0x6f,
	0xbe, 0xf3, 0xf9, 0xfc, 0x7c, 0xc7, 0xf0, 0x7f, 0x96, 0x0b, 0x25, 0x4e, 0x45, 0x4e, 0x59, 0x6e,
	0x7f, 0x23, 0x83, 0xa0, 0xff, 0x12, 0x11, 0x8d, 0xf9, 0x30, 0x17, 0x91, 0x64, 0xf9, 0x67, 0x3e,
	0x64, 0x91, 0xb9, 0x6d, 0x1e, 0x25, 0x42, 0x24, 0x23, 0x76, 0x6a, 0x58, 0x57, 0x93, 0xeb, 0x53,
	0xc5, 0xc7, 0x4c, 0x2a, 0x32, 0xce, 0x6c, 0x60, 0xf3, 0xe0, 0x36, 0x81, 0xa4, 0x53, 0x7b, 0x85,
	0x1f, 0xc2, 0xe6, 0x5b, 0x2d, 0x72, 0x41, 0xd1, 0x01, 0x6c, 0x19, 0xbd, 0x01, 0xa7, 0x0d, 0xaf,
	0xe5, 0xb5, 0x6b, 0xf1, 0xa6, 0xb0, 0x57, 0xf8, 0xbb, 0x07, 0x81, 0xa5, 0xa5, 0xd7, 0x02, 0xed,
	0x40, 0x75, 0x46, 0xa9, 0x72, 0x8a, 0xee, 0x03, 0x64, 0x64, 0x3a, 0x90, 0x8a, 0xa8, 0x89, 0x6c,
	0x54, 0x5b, 0x5e, 0xdb, 0x8f, 0x83, 0x8c, 0x4c, 0xfb, 0x06, 0x40, 0x47, 0x10, 0xca, 0x8f, 0x3c,
	0x2b, 0xee, 0x6b, 0xe6, 0x1e, 0x34, 0xe4, 0x08, 0xfb, 0xe0, 0x67, 0x39, 0x1f, 0xb2, 0x46, 0xbd,
	0xe5, 0xb5, 0xbd, 0xd8, 0x1e, 0xd0, 0x73, 0xd8, 0xb6, 0xe9, 0x50, 0xa6, 0x08, 0x1f, 0x35, 0xfc,
	0x56, 0xad, 0x1d, 0x76, 0x8e, 0xa3, 0xbb, 0x9b, 0x10, 0x99, 0xf4, 0xba, 0x86, 0x1a, 0x87, 0x62,
	0x7e, 0xc0, 0x3f, 0x3c, 0x08, 0x17, 0x2e, 0xef, 0xcc, 0x3e, 0x17, 0x74, 0x32, 0x54, 0xba, 0xf0,
	0xaa, 0xc1, 0x03, 0x87, 0x5c, 0x50, 0x9d, 0x7d, 0x71, 0x9d, 0x4e, 0xc6, 0x45, 0xf6, 0x0e, 0x7a,
	0x33, 0x19, 0xa3, 0x13, 0xd8, 0x2d, 0x08, 0x92, 0xdf, 0x30, 0x2d, 0x52, 0x37, 0x22, 0x7f, 0x39,
	0xb8, 0xcf, 0x6f, 0xd8, 0x05, 0x45, 0xc7, 0x50, 0x00, 0x03, 0x5b, 0xad, 0x6f, 0x58, 0xdb, 0x0e,
	0xec, 0x99, 0xa2, 0x17, 0x67, 0xb0, 0xf1, 0xfb, 0x0c, 0xbe, 0x7a, 0xb0, 0x67, 0xea, 0xe8, 0x91,
	0x84, 0xc5, 0xec, 0xd3, 0x84, 0x49, 0x85, 0x10, 0xd4, 0x33, 0x92, 0x30, 0x57, 0x8e, 0x79, 0x46,
	0xf7, 0x20, 0xd0, 0xff, 0x26, 0x1b, 0x57, 0xcf, 0x96, 0x06, 0x74, 0x1e, 0xe8, 0x15, 0xc0, 0x50,
	0xa4, 0x94, 0x2b, 0x2e, 0x52, 0x3b, 0x8b, 0xb0, 0xf3, 0x68, 0x65, 0x4f, 0xf5, 0xeb, 0xce, 0x66,
	0x21, 0xf1, 0x42, 0x38, 0xfe, 0xe9, 0xc1, 0x3f, 0x77, 0x70, 0x6e, 0x19, 0xc2, 0x2b, 0x31, 0x44,
	0xf5, 0x0f, 0x43, 0x1c, 0x3a, 0xb7, 0x9d, 0x09, 0xca, 0x4c, 0x8e, 0x41, 0x3c, 0x07, 0x50, 0x17,
	0xf6, 0x6c, 0x8f, 0xa4, 0x22, 0xb9, 0x1a, 0x68, 0xb3, 0x9b, 0x8e, 0x87, 0x9d, 0x66, 0x64, 0x8d,
	0x1e, 0x15, 0x46, 0x8f, 0x2e, 0x8b, 0x4d, 0x88, 0x77, 0x4c, 0x4c, 0x5f, 0x87, 0x68, 0x10, 0x3d,
	0x05, 0x8b, 0x0c, 0x58, 0x4a, 0xad, 0x86, 0x5f, 0xaa, 0x61, 0x0d, 0x79, 0x9e, 0x52, 0x0d, 0xe1,
	0x6f, 0x1e, 0xec, 0xcc, 0xaa, 0xa7, 0xaf, 0xb9, 0x54, 0xda, 0xc9, 0x4a, 0x28, 0x32, 0x72, 0xf3,
	0xb0, 0x87, 0xd9, 0x90, 0xaa, 0xcb, 0x86, 0x54, 0xbb, 0x35, 0x24, 0xbd, 0x10, 0x24, 0x61, 0xd2,
	0x19, 0xc9, 0x1e, 0xd0, 0x13, 0xa8, 0x77, 0x89, 0x22, 0x6e, 0x11, 0x1e, 0xac, 0x1c, 0x9a, 0xde,
	0xd3, 0xd8, 0xd0, 0xf1, 0x21, 0x6c, 0xc5, 0x4c, 0x66, 0x22, 0x95, 0x0c, 0xed, 0x41, 0x6d, 0x2c,
	0x13, 0x93, 0x5d, 0x10, 0xeb, 0x47, 0x7c, 0x0e, 0x41, 0x6f, 0x36, 0x98, 0xe5, 0x5f, 0x80, 0x92,
	0x1d, 0xc7, 0x2f, 0x01, 0xfa, 0xf3, 0xf9, 0xad, 0xd0, 0x29, 0x9b, 0x7d, 0xe7, 0x8b, 0x0f, 0xbe,
	0x29, 0x01, 0x5d, 0xc2, 0xf6, 0x0b, 0xa6, 0xcc, 0xf3, 0xb3, 0xa9, 0x0e, 0x5d, 0x5d, 0x31, 0x6d,
	0x96, 0xb7, 0x04, 0x57, 0x50, 0x02, 0x7f, 0x17, 0xaa, 0xf3, 0xb9, 0xb5, 0x4b, 0x37, 0xc0, 0x2d,
	0x5c, 0xf3, 0xa4, 0x94, 0x69, 0x14, 0x71, 0x05, 0xf5, 0x21, 0x3c, 0xcb, 0x19, 0x51, 0xcc, 0x56,
	0x53, 0x9e, 0x5c, 0xb3, 0xac, 0x40, 0x5c, 0x41, 0xef, 0x61, 0xb7, 0xcb, 0x46, 0xcc, 0x89, 0xae,
	0xd7, 0x96, 0xd6, 0x32, 0x42, 0x61, 0x0b, 0x5c, 0x41, 0x1f, 0x60, 0xff, 0x5d, 0x46, 0x8b, 0x64,
	0xe7, 0x8e, 0x58, 0x9a, 0xf5, 0x8c, 0xb2, 0x96, 0xfc, 0x00, 0xfe, 0x5d, 0x90, 0x5f, 0x70, 0x0a,
	0x5e, 0x16, 0x3c, 0xe7, 0xac, 0xf5, 0x82, 0x4b, 0x08, 0x17, 0x5e, 0xb0, 0x4e, 0xb3, 0xd7, 0x50,
	0xed, 0x55, 0x7a, 0xde, 0xd5, 0x86, 0xf9, 0x0e, 0x3c, 0xfe, 0x15, 0x00, 0x00, 0xff, 0xff, 0x28,
	0xbc, 0xcf, 0x0f, 0x96, 0x07, 0x00, 0x00,
}
