// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.23.2
// source: order/order.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderId) Reset() {
	*x = OrderId{}
	mi := &file_order_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderId) ProtoMessage() {}

func (x *OrderId) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderId.ProtoReflect.Descriptor instead.
func (*OrderId) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderId) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type OrderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PayStatus     int32                  `protobuf:"varint,2,opt,name=pay_status,json=payStatus,proto3" json:"pay_status,omitempty"`
	ShipStatus    int32                  `protobuf:"varint,3,opt,name=ship_status,json=shipStatus,proto3" json:"ship_status,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	OrderDetail   []*OrderDetail         `protobuf:"bytes,5,rep,name=order_detail,json=orderDetail,proto3" json:"order_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	mi := &file_order_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderInfo) GetPayStatus() int32 {
	if x != nil {
		return x.PayStatus
	}
	return 0
}

func (x *OrderInfo) GetShipStatus() int32 {
	if x != nil {
		return x.ShipStatus
	}
	return 0
}

func (x *OrderInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderInfo) GetOrderDetail() []*OrderDetail {
	if x != nil {
		return x.OrderDetail
	}
	return nil
}

type OrderDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductNum    int32                  `protobuf:"varint,3,opt,name=product_num,json=productNum,proto3" json:"product_num,omitempty"`
	ProductSizeId int64                  `protobuf:"varint,4,opt,name=product_size_id,json=productSizeId,proto3" json:"product_size_id,omitempty"`
	ProductPrice  int64                  `protobuf:"varint,5,opt,name=product_price,json=productPrice,proto3" json:"product_price,omitempty"`
	OrderId       int64                  `protobuf:"varint,6,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDetail) Reset() {
	*x = OrderDetail{}
	mi := &file_order_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetail) ProtoMessage() {}

func (x *OrderDetail) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetail.ProtoReflect.Descriptor instead.
func (*OrderDetail) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderDetail) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderDetail) GetProductNum() int32 {
	if x != nil {
		return x.ProductNum
	}
	return 0
}

func (x *OrderDetail) GetProductSizeId() int64 {
	if x != nil {
		return x.ProductSizeId
	}
	return 0
}

func (x *OrderDetail) GetProductPrice() int64 {
	if x != nil {
		return x.ProductPrice
	}
	return 0
}

func (x *OrderDetail) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type OrderPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Conditions    *OrderPageConditions   `protobuf:"bytes,3,opt,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPageRequest) Reset() {
	*x = OrderPageRequest{}
	mi := &file_order_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPageRequest) ProtoMessage() {}

func (x *OrderPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPageRequest.ProtoReflect.Descriptor instead.
func (*OrderPageRequest) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{3}
}

func (x *OrderPageRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *OrderPageRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *OrderPageRequest) GetConditions() *OrderPageConditions {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type OrderPageConditions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PayStatus      int32                  `protobuf:"varint,1,opt,name=pay_status,json=payStatus,proto3" json:"pay_status,omitempty"`
	ShipStatus     int32                  `protobuf:"varint,2,opt,name=ship_status,json=shipStatus,proto3" json:"ship_status,omitempty"`
	OrderCode      string                 `protobuf:"bytes,3,opt,name=OrderCode,proto3" json:"OrderCode,omitempty"`
	OrderStartTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=order_start_time,json=orderStartTime,proto3" json:"order_start_time,omitempty"`
	OrderEndTime   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=order_end_time,json=orderEndTime,proto3" json:"order_end_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderPageConditions) Reset() {
	*x = OrderPageConditions{}
	mi := &file_order_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPageConditions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPageConditions) ProtoMessage() {}

func (x *OrderPageConditions) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPageConditions.ProtoReflect.Descriptor instead.
func (*OrderPageConditions) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{4}
}

func (x *OrderPageConditions) GetPayStatus() int32 {
	if x != nil {
		return x.PayStatus
	}
	return 0
}

func (x *OrderPageConditions) GetShipStatus() int32 {
	if x != nil {
		return x.ShipStatus
	}
	return 0
}

func (x *OrderPageConditions) GetOrderCode() string {
	if x != nil {
		return x.OrderCode
	}
	return ""
}

func (x *OrderPageConditions) GetOrderStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.OrderStartTime
	}
	return nil
}

func (x *OrderPageConditions) GetOrderEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.OrderEndTime
	}
	return nil
}

type OrderPagedList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Pages         int64                  `protobuf:"varint,4,opt,name=pages,proto3" json:"pages,omitempty"`
	Data          []*OrderInfo           `protobuf:"bytes,5,rep,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPagedList) Reset() {
	*x = OrderPagedList{}
	mi := &file_order_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPagedList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPagedList) ProtoMessage() {}

func (x *OrderPagedList) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPagedList.ProtoReflect.Descriptor instead.
func (*OrderPagedList) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{5}
}

func (x *OrderPagedList) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OrderPagedList) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *OrderPagedList) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *OrderPagedList) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *OrderPagedList) GetData() []*OrderInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_order_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{6}
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type PayStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PayStatus     int32                  `protobuf:"varint,2,opt,name=pay_status,json=payStatus,proto3" json:"pay_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayStatus) Reset() {
	*x = PayStatus{}
	mi := &file_order_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayStatus) ProtoMessage() {}

func (x *PayStatus) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayStatus.ProtoReflect.Descriptor instead.
func (*PayStatus) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{7}
}

func (x *PayStatus) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PayStatus) GetPayStatus() int32 {
	if x != nil {
		return x.PayStatus
	}
	return 0
}

type ShipStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ShipStatus    int32                  `protobuf:"varint,2,opt,name=ship_status,json=shipStatus,proto3" json:"ship_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipStatus) Reset() {
	*x = ShipStatus{}
	mi := &file_order_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipStatus) ProtoMessage() {}

func (x *ShipStatus) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipStatus.ProtoReflect.Descriptor instead.
func (*ShipStatus) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{8}
}

func (x *ShipStatus) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ShipStatus) GetShipStatus() int32 {
	if x != nil {
		return x.ShipStatus
	}
	return 0
}

type PayNotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutTradeNo    string                 `protobuf:"bytes,1,opt,name=OutTradeNo,proto3" json:"OutTradeNo,omitempty"`
	TradeNo       string                 `protobuf:"bytes,2,opt,name=TradeNo,proto3" json:"TradeNo,omitempty"`
	StatusCode    string                 `protobuf:"bytes,3,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayNotifyRequest) Reset() {
	*x = PayNotifyRequest{}
	mi := &file_order_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayNotifyRequest) ProtoMessage() {}

func (x *PayNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayNotifyRequest.ProtoReflect.Descriptor instead.
func (*PayNotifyRequest) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{9}
}

func (x *PayNotifyRequest) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *PayNotifyRequest) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *PayNotifyRequest) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

type PayNotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    string                 `protobuf:"bytes,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayNotifyResponse) Reset() {
	*x = PayNotifyResponse{}
	mi := &file_order_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayNotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayNotifyResponse) ProtoMessage() {}

func (x *PayNotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayNotifyResponse.ProtoReflect.Descriptor instead.
func (*PayNotifyResponse) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{10}
}

func (x *PayNotifyResponse) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *PayNotifyResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_order_order_proto protoreflect.FileDescriptor

const file_order_order_proto_rawDesc = "" +
	"\n" +
	"\x11order/order.proto\x12\x10go.micro.service\x1a\x1fgoogle/protobuf/timestamp.proto\"$\n" +
	"\aOrderId\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\"\xb3\x01\n" +
	"\tOrderInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"pay_status\x18\x02 \x01(\x05R\tpayStatus\x12\x1f\n" +
	"\vship_status\x18\x03 \x01(\x05R\n" +
	"shipStatus\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12@\n" +
	"\forder_detail\x18\x05 \x03(\v2\x1d.go.micro.service.OrderDetailR\vorderDetail\"\xc5\x01\n" +
	"\vOrderDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x1f\n" +
	"\vproduct_num\x18\x03 \x01(\x05R\n" +
	"productNum\x12&\n" +
	"\x0fproduct_size_id\x18\x04 \x01(\x03R\rproductSizeId\x12#\n" +
	"\rproduct_price\x18\x05 \x01(\x03R\fproductPrice\x12\x19\n" +
	"\border_id\x18\x06 \x01(\x03R\aorderId\"\x8a\x01\n" +
	"\x10OrderPageRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12E\n" +
	"\n" +
	"conditions\x18\x03 \x01(\v2%.go.micro.service.OrderPageConditionsR\n" +
	"conditions\"\xfb\x01\n" +
	"\x13OrderPageConditions\x12\x1d\n" +
	"\n" +
	"pay_status\x18\x01 \x01(\x05R\tpayStatus\x12\x1f\n" +
	"\vship_status\x18\x02 \x01(\x05R\n" +
	"shipStatus\x12\x1c\n" +
	"\tOrderCode\x18\x03 \x01(\tR\tOrderCode\x12D\n" +
	"\x10order_start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0eorderStartTime\x12@\n" +
	"\x0eorder_end_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\forderEndTime\"\x9e\x01\n" +
	"\x0eOrderPagedList\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\x12\x14\n" +
	"\x05pages\x18\x04 \x01(\x03R\x05pages\x12/\n" +
	"\x04Data\x18\x05 \x03(\v2\x1b.go.micro.service.OrderInfoR\x04Data\"\x1c\n" +
	"\bResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"E\n" +
	"\tPayStatus\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x1d\n" +
	"\n" +
	"pay_status\x18\x02 \x01(\x05R\tpayStatus\"H\n" +
	"\n" +
	"ShipStatus\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x1f\n" +
	"\vship_status\x18\x02 \x01(\x05R\n" +
	"shipStatus\"l\n" +
	"\x10PayNotifyRequest\x12\x1e\n" +
	"\n" +
	"OutTradeNo\x18\x01 \x01(\tR\n" +
	"OutTradeNo\x12\x18\n" +
	"\aTradeNo\x18\x02 \x01(\tR\aTradeNo\x12\x1e\n" +
	"\n" +
	"StatusCode\x18\x03 \x01(\tR\n" +
	"StatusCode\"E\n" +
	"\x11PayNotifyResponse\x12\x1e\n" +
	"\n" +
	"StatusCode\x18\x01 \x01(\tR\n" +
	"StatusCode\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg2\xa9\x01\n" +
	"\x05Order\x12H\n" +
	"\fGetOrderById\x12\x19.go.micro.service.OrderId\x1a\x1b.go.micro.service.OrderInfo\"\x00\x12V\n" +
	"\tPayNotify\x12\".go.micro.service.PayNotifyRequest\x1a#.go.micro.service.PayNotifyResponse\"\x00B\x0fZ\r./proto/orderb\x06proto3"

var (
	file_order_order_proto_rawDescOnce sync.Once
	file_order_order_proto_rawDescData []byte
)

func file_order_order_proto_rawDescGZIP() []byte {
	file_order_order_proto_rawDescOnce.Do(func() {
		file_order_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_order_proto_rawDesc), len(file_order_order_proto_rawDesc)))
	})
	return file_order_order_proto_rawDescData
}

var file_order_order_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_order_order_proto_goTypes = []any{
	(*OrderId)(nil),               // 0: go.micro.service.OrderId
	(*OrderInfo)(nil),             // 1: go.micro.service.OrderInfo
	(*OrderDetail)(nil),           // 2: go.micro.service.OrderDetail
	(*OrderPageRequest)(nil),      // 3: go.micro.service.OrderPageRequest
	(*OrderPageConditions)(nil),   // 4: go.micro.service.OrderPageConditions
	(*OrderPagedList)(nil),        // 5: go.micro.service.OrderPagedList
	(*Response)(nil),              // 6: go.micro.service.Response
	(*PayStatus)(nil),             // 7: go.micro.service.PayStatus
	(*ShipStatus)(nil),            // 8: go.micro.service.ShipStatus
	(*PayNotifyRequest)(nil),      // 9: go.micro.service.PayNotifyRequest
	(*PayNotifyResponse)(nil),     // 10: go.micro.service.PayNotifyResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_order_order_proto_depIdxs = []int32{
	2,  // 0: go.micro.service.OrderInfo.order_detail:type_name -> go.micro.service.OrderDetail
	4,  // 1: go.micro.service.OrderPageRequest.conditions:type_name -> go.micro.service.OrderPageConditions
	11, // 2: go.micro.service.OrderPageConditions.order_start_time:type_name -> google.protobuf.Timestamp
	11, // 3: go.micro.service.OrderPageConditions.order_end_time:type_name -> google.protobuf.Timestamp
	1,  // 4: go.micro.service.OrderPagedList.Data:type_name -> go.micro.service.OrderInfo
	0,  // 5: go.micro.service.Order.GetOrderById:input_type -> go.micro.service.OrderId
	9,  // 6: go.micro.service.Order.PayNotify:input_type -> go.micro.service.PayNotifyRequest
	1,  // 7: go.micro.service.Order.GetOrderById:output_type -> go.micro.service.OrderInfo
	10, // 8: go.micro.service.Order.PayNotify:output_type -> go.micro.service.PayNotifyResponse
	7,  // [7:9] is the sub-list for method output_type
	5,  // [5:7] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_order_order_proto_init() }
func file_order_order_proto_init() {
	if File_order_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_order_proto_rawDesc), len(file_order_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_order_proto_goTypes,
		DependencyIndexes: file_order_order_proto_depIdxs,
		MessageInfos:      file_order_order_proto_msgTypes,
	}.Build()
	File_order_order_proto = out.File
	file_order_order_proto_goTypes = nil
	file_order_order_proto_depIdxs = nil
}
