// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: github.com/zhanshen02154/order/order.proto

package order

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Order service

func NewOrderEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Order service

type OrderService interface {
	GetOrderById(ctx context.Context, in *OrderId, opts ...client.CallOption) (*OrderInfo, error)
	GetOrderPagedList(ctx context.Context, in *OrderPageRequest, opts ...client.CallOption) (*OrderPagedList, error)
	CreateOrder(ctx context.Context, in *OrderInfo, opts ...client.CallOption) (*OrderId, error)
	DeleteOrderById(ctx context.Context, in *OrderId, opts ...client.CallOption) (*Response, error)
	UpdateOrderPayStatus(ctx context.Context, in *PayStatus, opts ...client.CallOption) (*Response, error)
	UpdateOrderShipStatus(ctx context.Context, in *ShipStatus, opts ...client.CallOption) (*Response, error)
	UpdateOrder(ctx context.Context, in *OrderInfo, opts ...client.CallOption) (*Response, error)
}

type orderService struct {
	c    client.Client
	name string
}

func NewOrderService(name string, c client.Client) OrderService {
	return &orderService{
		c:    c,
		name: name,
	}
}

func (c *orderService) GetOrderById(ctx context.Context, in *OrderId, opts ...client.CallOption) (*OrderInfo, error) {
	req := c.c.NewRequest(c.name, "Order.GetOrderById", in)
	out := new(OrderInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) GetOrderPagedList(ctx context.Context, in *OrderPageRequest, opts ...client.CallOption) (*OrderPagedList, error) {
	req := c.c.NewRequest(c.name, "Order.GetOrderPagedList", in)
	out := new(OrderPagedList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) CreateOrder(ctx context.Context, in *OrderInfo, opts ...client.CallOption) (*OrderId, error) {
	req := c.c.NewRequest(c.name, "Order.CreateOrder", in)
	out := new(OrderId)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) DeleteOrderById(ctx context.Context, in *OrderId, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Order.DeleteOrderById", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) UpdateOrderPayStatus(ctx context.Context, in *PayStatus, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Order.UpdateOrderPayStatus", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) UpdateOrderShipStatus(ctx context.Context, in *ShipStatus, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Order.UpdateOrderShipStatus", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) UpdateOrder(ctx context.Context, in *OrderInfo, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Order.UpdateOrder", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Order service

type OrderHandler interface {
	GetOrderById(context.Context, *OrderId, *OrderInfo) error
	GetOrderPagedList(context.Context, *OrderPageRequest, *OrderPagedList) error
	CreateOrder(context.Context, *OrderInfo, *OrderId) error
	DeleteOrderById(context.Context, *OrderId, *Response) error
	UpdateOrderPayStatus(context.Context, *PayStatus, *Response) error
	UpdateOrderShipStatus(context.Context, *ShipStatus, *Response) error
	UpdateOrder(context.Context, *OrderInfo, *Response) error
}

func RegisterOrderHandler(s server.Server, hdlr OrderHandler, opts ...server.HandlerOption) error {
	type order interface {
		GetOrderById(ctx context.Context, in *OrderId, out *OrderInfo) error
		GetOrderPagedList(ctx context.Context, in *OrderPageRequest, out *OrderPagedList) error
		CreateOrder(ctx context.Context, in *OrderInfo, out *OrderId) error
		DeleteOrderById(ctx context.Context, in *OrderId, out *Response) error
		UpdateOrderPayStatus(ctx context.Context, in *PayStatus, out *Response) error
		UpdateOrderShipStatus(ctx context.Context, in *ShipStatus, out *Response) error
		UpdateOrder(ctx context.Context, in *OrderInfo, out *Response) error
	}
	type Order struct {
		order
	}
	h := &orderHandler{hdlr}
	return s.Handle(s.NewHandler(&Order{h}, opts...))
}

type orderHandler struct {
	OrderHandler
}

func (h *orderHandler) GetOrderById(ctx context.Context, in *OrderId, out *OrderInfo) error {
	return h.OrderHandler.GetOrderById(ctx, in, out)
}

func (h *orderHandler) GetOrderPagedList(ctx context.Context, in *OrderPageRequest, out *OrderPagedList) error {
	return h.OrderHandler.GetOrderPagedList(ctx, in, out)
}

func (h *orderHandler) CreateOrder(ctx context.Context, in *OrderInfo, out *OrderId) error {
	return h.OrderHandler.CreateOrder(ctx, in, out)
}

func (h *orderHandler) DeleteOrderById(ctx context.Context, in *OrderId, out *Response) error {
	return h.OrderHandler.DeleteOrderById(ctx, in, out)
}

func (h *orderHandler) UpdateOrderPayStatus(ctx context.Context, in *PayStatus, out *Response) error {
	return h.OrderHandler.UpdateOrderPayStatus(ctx, in, out)
}

func (h *orderHandler) UpdateOrderShipStatus(ctx context.Context, in *ShipStatus, out *Response) error {
	return h.OrderHandler.UpdateOrderShipStatus(ctx, in, out)
}

func (h *orderHandler) UpdateOrder(ctx context.Context, in *OrderInfo, out *Response) error {
	return h.OrderHandler.UpdateOrder(ctx, in, out)
}
