// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: order/order.proto

package order

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Order service

func NewOrderEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Order service

type OrderService interface {
	GetOrderById(ctx context.Context, in *OrderId, opts ...client.CallOption) (*OrderInfo, error)
	PayNotify(ctx context.Context, in *PayNotifyRequest, opts ...client.CallOption) (*PayNotifyResponse, error)
}

type orderService struct {
	c    client.Client
	name string
}

func NewOrderService(name string, c client.Client) OrderService {
	return &orderService{
		c:    c,
		name: name,
	}
}

func (c *orderService) GetOrderById(ctx context.Context, in *OrderId, opts ...client.CallOption) (*OrderInfo, error) {
	req := c.c.NewRequest(c.name, "Order.GetOrderById", in)
	out := new(OrderInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) PayNotify(ctx context.Context, in *PayNotifyRequest, opts ...client.CallOption) (*PayNotifyResponse, error) {
	req := c.c.NewRequest(c.name, "Order.PayNotify", in)
	out := new(PayNotifyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Order service

type OrderHandler interface {
	GetOrderById(context.Context, *OrderId, *OrderInfo) error
	PayNotify(context.Context, *PayNotifyRequest, *PayNotifyResponse) error
}

func RegisterOrderHandler(s server.Server, hdlr OrderHandler, opts ...server.HandlerOption) error {
	type order interface {
		GetOrderById(ctx context.Context, in *OrderId, out *OrderInfo) error
		PayNotify(ctx context.Context, in *PayNotifyRequest, out *PayNotifyResponse) error
	}
	type Order struct {
		order
	}
	h := &orderHandler{hdlr}
	return s.Handle(s.NewHandler(&Order{h}, opts...))
}

type orderHandler struct {
	OrderHandler
}

func (h *orderHandler) GetOrderById(ctx context.Context, in *OrderId, out *OrderInfo) error {
	return h.OrderHandler.GetOrderById(ctx, in, out)
}

func (h *orderHandler) PayNotify(ctx context.Context, in *PayNotifyRequest, out *PayNotifyResponse) error {
	return h.OrderHandler.PayNotify(ctx, in, out)
}
